# Generated by Django 4.0.7 on 2023-10-02 13:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveBigIntegerField()),
                ('sender_address', models.CharField(max_length=100, null=True)),
                ('receiver_address', models.CharField(max_length=100, null=True)),
                ('SKU', models.CharField(max_length=100, unique=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'IN_TRANSIT'), (1, 'INBOUND_SCAN'), (2, 'DELIVERY'), (3, 'SCANNED'), (4, 'TRANSIT')], default=0)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('carrier', models.CharField(max_length=100, null=True)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='shipment.article')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
